--CREATE TABLE if not exists Manga
--(
--  id_manga INT NOT NULL,
--  nome INT NOT NULL,
--  total_caps INT NOT NULL,
--  temporadas INT NOT NULL,
--  tipo INT NOT NULL,
--  PRIMARY KEY (id_manga)
--);
--
--CREATE TABLE if not exists Usuario
--(
--  id_user INT NOT NULL,
--  nome INT NOT NULL,
--  PRIMARY KEY (id_user)
--);u
--
--CREATE TABLE if not exists Genero
--(
--  id_genero INT NOT NULL,
--  genero INT NOT NULL,
--  PRIMARY KEY (id_genero)
--);

--CREATE TABLE if not exists "User_Manga"
--(
--  atual_cap INT NOT NULL,
--  atual_temporada INT NOT NULL,
--  id_user INT NOT NULL,
--  id_manga INT NOT NULL,
--  PRIMARY KEY (id_user, id_manga),
--  FOREIGN KEY (id_user) REFERENCES Usuario(id_user),
--  FOREIGN KEY (id_manga) REFERENCES Manga(id_manga)
--);
--
--CREATE TABLE if not exists Manga_Genero
--(
--  id_genero INT NOT NULL,
--  id_manga INT NOT NULL,
--  PRIMARY KEY (id_genero, id_manga),
--  FOREIGN KEY (id_genero) REFERENCES Genero(id_genero),
--  FOREIGN KEY (id_manga) REFERENCES Manga(id_manga)
--);
--
--CREATE TABLE if not exists Site
--(
--  url INT NOT NULL,
--  ativo INT NOT NULL,
--  id_site INT NOT NULL,
--  id_manga INT NOT NULL,
--  PRIMARY KEY (id_site),
--  FOREIGN KEY (id_manga) REFERENCES Manga(id_manga)
--);

CREATE TABLE "users" (
  "id_user" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "manga_user" (
  "id" int,
  "atual_cap" int,
  "atual_temporada" int,
  "userId" int,
  "mangaId" int
);

CREATE TABLE "mangas" (
  "id_manga" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "total_caps" int,
  "temporadas" int,
  "tipo" int
);

CREATE TABLE "sites" (
  "id_site" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar,
  "ativo" bool,
  "mangaId" int
);

CREATE TABLE "genero" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "genero" varchar
);

CREATE TABLE "Manga_Genero" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_manga" int,
  "id_genero" int
);

ALTER TABLE "sites" ADD FOREIGN KEY ("mangaId") REFERENCES "mangas" ("id_manga");

ALTER TABLE "manga_user" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id_user");

ALTER TABLE "manga_user" ADD FOREIGN KEY ("mangaId") REFERENCES "mangas" ("id_manga");

ALTER TABLE "Manga_Genero" ADD FOREIGN KEY ("id_genero") REFERENCES "genero" ("id");

ALTER TABLE "Manga_Genero" ADD FOREIGN KEY ("id_manga") REFERENCES "mangas" ("id_manga");


select * from users u 
--
insert into users (name) values ('Alvaro Coelho Jesus'); 



select * from mangas m
select * from genero g 

insert into genero (genero)
values
('Outro'),
('Shounen'),
('Shoujo'),
('Hentai (Seijin)'),
('Ecchi'),
('Yaoi'),
('Yuri'),
('Gekigá'),
('Seinen'),
('Josei')















